# Generated by Django 5.0.6 on 2024-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('short', models.TextField()),
                ('province', models.TextField()),
                ('city', models.TextField()),
                ('body', models.TextField()),
                ('thumbnail', models.TextField()),
            ],
            options={
                'db_table': 'destinations',
            },
        ),
    ]
