# Generated by Django 5.0.6 on 2024-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('published_at', models.DateTimeField(verbose_name='date published')),
                ('link', models.TextField()),
                ('short', models.TextField()),
                ('body', models.TextField()),
                ('thumbnail', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
